name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    needs: [build, test, integration-tests]
    name: CI
    runs-on: "ubuntu-latest"
    steps:
      - name: Done
        run: exit 0

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose

  test:
    name: Test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: cargo test

  integration-tests:
    name: Integration Tests (Examples)
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: Build examples
        run: cargo build --release --examples
      - name: Test naive example with FASTQ
        run: cargo run --release --example naive -- data/sample.fastq
      - name: Test naive example with FASTA
        run: cargo run --release --example naive -- data/sample.fasta
      - name: Test parallel example with FASTQ (1 thread)
        run: cargo run --release --example parallel -- data/sample.fastq 1
      - name: Test parallel example with FASTQ (2 threads)
        run: cargo run --release --example parallel -- data/sample.fastq 2
      - name: Test parallel example with FASTA (1 thread)
        run: cargo run --release --example parallel -- data/sample.fasta 1
      - name: Test parallel example with FASTA (2 threads)
        run: cargo run --release --example parallel -- data/sample.fasta 2
      - name: Test interleaved example
        run: cargo run --release --example interleaved -- data/interleaved.fastq
      - name: Test multiline FASTA example
        run: cargo run --release --example multiline_fasta -- data/multiline.fasta
      - name: Test paired parallel example
        run: cargo run --release --example paired_parallel -- data/sample_R1.fastq data/sample_R2.fastq
      - name: Test reloading example
        run: cargo run --release --example reloading -- data/sample.fastq
      - name: Test reloading parallel example
        run: cargo run --release --example reloading_parallel -- data/sample.fastq
